// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XVOICEREC_H
#define XVOICEREC_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xvoicerec_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Voice_rec_BaseAddress;
} XVoicerec_Config;
#endif

typedef struct {
    u32 Voice_rec_BaseAddress;
    u32 IsReady;
} XVoicerec;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XVoicerec_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XVoicerec_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XVoicerec_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XVoicerec_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XVoicerec_Initialize(XVoicerec *InstancePtr, u16 DeviceId);
XVoicerec_Config* XVoicerec_LookupConfig(u16 DeviceId);
int XVoicerec_CfgInitialize(XVoicerec *InstancePtr, XVoicerec_Config *ConfigPtr);
#else
int XVoicerec_Initialize(XVoicerec *InstancePtr, const char* InstanceName);
int XVoicerec_Release(XVoicerec *InstancePtr);
#endif

void XVoicerec_Start(XVoicerec *InstancePtr);
u32 XVoicerec_IsDone(XVoicerec *InstancePtr);
u32 XVoicerec_IsIdle(XVoicerec *InstancePtr);
u32 XVoicerec_IsReady(XVoicerec *InstancePtr);
void XVoicerec_EnableAutoRestart(XVoicerec *InstancePtr);
void XVoicerec_DisableAutoRestart(XVoicerec *InstancePtr);
u32 XVoicerec_Get_return(XVoicerec *InstancePtr);

void XVoicerec_Set_new_sample(XVoicerec *InstancePtr, u32 Data);
u32 XVoicerec_Get_new_sample(XVoicerec *InstancePtr);

void XVoicerec_InterruptGlobalEnable(XVoicerec *InstancePtr);
void XVoicerec_InterruptGlobalDisable(XVoicerec *InstancePtr);
void XVoicerec_InterruptEnable(XVoicerec *InstancePtr, u32 Mask);
void XVoicerec_InterruptDisable(XVoicerec *InstancePtr, u32 Mask);
void XVoicerec_InterruptClear(XVoicerec *InstancePtr, u32 Mask);
u32 XVoicerec_InterruptGetEnabled(XVoicerec *InstancePtr);
u32 XVoicerec_InterruptGetStatus(XVoicerec *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
