// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xvoicerec.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XVoicerec_CfgInitialize(XVoicerec *InstancePtr, XVoicerec_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Voice_rec_BaseAddress = ConfigPtr->Voice_rec_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XVoicerec_Start(XVoicerec *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_CTRL) & 0x80;
    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_CTRL, Data | 0x01);
}

u32 XVoicerec_IsDone(XVoicerec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XVoicerec_IsIdle(XVoicerec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XVoicerec_IsReady(XVoicerec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XVoicerec_EnableAutoRestart(XVoicerec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_CTRL, 0x80);
}

void XVoicerec_DisableAutoRestart(XVoicerec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_CTRL, 0);
}

u32 XVoicerec_Get_return(XVoicerec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_AP_RETURN);
    return Data;
}
void XVoicerec_Set_new_sample(XVoicerec *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_NEW_SAMPLE_DATA, Data);
}

u32 XVoicerec_Get_new_sample(XVoicerec *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_NEW_SAMPLE_DATA);
    return Data;
}

void XVoicerec_InterruptGlobalEnable(XVoicerec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_GIE, 1);
}

void XVoicerec_InterruptGlobalDisable(XVoicerec *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_GIE, 0);
}

void XVoicerec_InterruptEnable(XVoicerec *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_IER);
    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_IER, Register | Mask);
}

void XVoicerec_InterruptDisable(XVoicerec *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_IER);
    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_IER, Register & (~Mask));
}

void XVoicerec_InterruptClear(XVoicerec *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVoicerec_WriteReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_ISR, Mask);
}

u32 XVoicerec_InterruptGetEnabled(XVoicerec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_IER);
}

u32 XVoicerec_InterruptGetStatus(XVoicerec *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XVoicerec_ReadReg(InstancePtr->Voice_rec_BaseAddress, XVOICEREC_VOICE_REC_ADDR_ISR);
}

